import type { Image } from "@/shared/types";

export const imagesData: Image[] = [
  {
    id: "20",
    author: "Aleks Dorohovich",
    title: "Creative desktop with laptop and smartphone",
    width: 918,
    height: 616,
    ext: "jpg",
    fileName: "sunset_over_lake.jpg",
  },
  {
    id: "35",
    author: "Shane Colella",
    title: "Mountain Peaks in Spring Surrounded",
    width: 2758,
    height: 3622,
    ext: "jpg",
    fileName: "mountain_peaks.jpg",
  },
  {
    id: "42",
    author: "Luke Chesser",
    width: 3456,
    height: 2304,
    title: "Morning in a cozy cafe",
    ext: "jpg",
    fileName: "calm_forest_morning.jpg",
  },
  {
    id: "43",
    author: "Oleg Chursin",
    title: "Old Town Alleyway Bathed in Warm Golden Sunlight",
    width: 1280,
    height: 831,
    ext: "jpg",
    fileName: "old_town_alleyway_sunlight.jpg",
  },
  {
    id: "57",
    author: "Nicholas Swanson",
    title: "Golden Wheat Fields",
    width: 2448,
    height: 3264,
    ext: "jpg",
    fileName: "golden_wheat_fields.jpg",
  },
  {
    id: "75",
    author: "Jessy Onyae",
    title: "Ocean Waves Crashing Against Rocky Shores at Sunset",
    width: 1999,
    height: 2998,
    ext: "jpg",
    fileName: "ocean_waves_rocky.jpg",
  },
  {
    id: "78",
    author: "Paul Evens",
    title: "Quiet Countryside Road",
    width: 1584,
    height: 2376,
    ext: "jpg",
    fileName: "quiet_countryside_road.jpg",
  },
  {
    id: "90",
    author: "Rula Sibai",
    title: "Blooming Spring Garden",
    width: 3000,
    height: 1992,
    ext: "jpg",
    fileName: "blooming_spring_garden.jpg",
  },
  {
    id: "106",
    author: "Arvee Marie",
    title: "Snowy Mountain Trail",
    width: 2592,
    height: 1728,
    ext: "jpg",
    fileName: "snowy_mountain_trail.jpg",
  },
  {
    id: "110",
    author: "Kenneth Thewissen",
    title: "Starry Night Sky Illuminated by the Milky Way",
    width: 5000,
    height: 3333,
    ext: "jpg",
    fileName: "starry_night_milky_way.jpg",
  },
  {
    id: "163",
    author: "Lyhn Nguyen",
    title: "Peaceful Riverside View",
    width: 2000,
    height: 1333,
    ext: "jpg",
    fileName: "peaceful_riverside_view.jpg",
  },
  {
    id: "21",
    author: "Alejandro Escamilla",
    title: "White shoes on the woody floor",
    width: 3008,
    height: 2008,
    ext: "jpg",
    fileName: "white_shoes_wooden_floor.jpg",
  },
  {
    id: "26",
    author: "Vadim Sherbakov",
    title: "Accessories",
    width: 4209,
    height: 2769,
    ext: "jpg",
    fileName: "accessories.jpg",
  },
  {
    id: "88",
    author: "Barcelona",
    title: "Car traffic",
    width: 1280,
    height: 1707,
    ext: "jpg",
    fileName: "car_traffic.jpg",
  },
  {
    id: "116",
    author: "Anton Sulsky",
    title: "Tuscany Hills",
    width: 3504,
    height: 2336,
    ext: "jpg",
    fileName: "tuscany_hills.jpg",
  },
].map((image) => ({
  ...image,
  thumbnail: `https://picsum.photos/id/${image.id}/400/300`,
  original: `https://picsum.photos/id/${image.id}/${image.width}/${image.height}`,
}));

//https://picsum.photos/id/26/4209/2769
